nb_etapes(2).
nb_coureurs(3).
nb_equipes(4).
nb_cartesSecondeCommence(5).
nb_cartesSecondeTirer(5).
carteSecondePlusBasse(1).
carteSecondePlusHaute(12).
nb_cartesSecondeRecurrence(8).
nb_cartesSecondeTotale(96).